
   /*Each new term in the Fibonacci sequence is generated by adding
    the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
  // RadwRock07 , pws you know it
#include <iostream>

using namespace std;

int main()
{
   unsigned long long f1{1}, f2{1}, f3{2}, sum{0};
   const long long limit{4000000};


    while(f3<limit)
    {
      f3=f1+f2;
      f1=f2;
      f2=f3;

      if(f3%2==0)
        sum+=f3;

    }

cout<<"Sum is: "<<sum<<endl;

    return 0;
}
